### ISSUE TITLE
Mouse zoom going to far on the tree map

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#110]
On the total expenditure tree map I was actually trying to scrool down the page, but instead it was possible to zoom the graph untill it disappear.

I am using a mac and firefox as my browser.

I will post a video in slack that shows the issue.

**Comment by edwinmp** [comment]
That's expected behaviour, happens with the map as well. The problem is the lack of control over the zoom feature i.e. adding a minimum & maximum zoom, or even turning it off completely. Couldn't find a solution for this, so I'm shelving this for now. Will leave it to the user to use it appropriately.

To reset the zoom, click the initial breadcrumb.

**Comment by edwinmp** [comment]
I disagree with the title though ... I think it's needed. Some of these portions are soo small that the only way to see their content or even hover over them is by zooming.

**Comment by k8hughes** [comment]
I think we do need to be able to do something, for me using a mac as scroll down the spotlight this just happened because of my mouse position scrolling down the page and it wasn't clear why / what was happening at first.
Once you've zoomed to the point that the graph disappears the only way I could get it back was to reload the whole page which is also not great.

**Comment by edwinmp** [comment]
You can return the chart to its original form by zooming in, or simply clicking the root breadcrumb button. Can't do anything about this at the moment, and if there's an urgency to it, I'd likely have to change libraries, or change the library code, cos the current chart library doesn't have any way to change this behaviour.

**Comment by edwinmp** [comment]
Also, since the map behaves the same way when scrolling, do we disable mouse-based zooming there as well?

**Comment by k8hughes** [comment]
Maybe we should ask Ben C to review and advise.

**Comment by edwinmp** [comment]
Hi @k8hughes are u satisfied with the fix for this?

**Comment by k8hughes** [comment]
Yes LGTM!
