### ISSUE TITLE
Regression: ability to add same location twice on location comparison page

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#131]
This shouldn't be allowed.

![image](https://user-images.githubusercontent.com/5672438/78243640-cc7bf100-74ec-11ea-974b-e732fb30fbb4.png)

**Comment by edwinmp** [comment]
@davidebukali pretty much assigning everything on location comparison to you :)

**Comment by k8hughes** [comment]
LGTM.
