### ISSUE TITLE
Some visualisation crash because their required 'relations' are not found

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#132]
![image](https://user-images.githubusercontent.com/5672438/78260927-399c8000-7507-11ea-8a5a-84d13fffdea0.png)

![image](https://user-images.githubusercontent.com/5672438/78261034-5cc72f80-7507-11ea-9f40-546e99bf4d0c.png)

**Comment by k8hughes** [comment]
LGTM
