### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#134]
Footer Twitter SVG image 404 error: <ul class="footer__social"><li><a href="https://twitter.com"><img src="svg/source/twitter.svg" alt="twitter"></a></li></ul> 
* Header and footer navigation links point to http://localhost
* Footer has Major text and Minor text below navigation
* Footer Subscribe here button points to https://www.google.com/

**Comment by edwinmp** [comment]
There's an issue for the icons (issue #157 ), and the rest are configuration issues or originated from me running on my local machine.
