### ISSUE TITLE
Mobile Nav doesn't open

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#135]
Mobile navigation doesn’t open (Chrome/Mac) - button doesn’t toggle on mouse click or keyboard interaction

**Comment by k8hughes** [comment]
I only have a android phone, but I have checked on that.  I have checked iphone on my browser and this seems to work also.

**Comment by k8hughes** [comment]
Josh tested this on iphone for me and found one of the drop downs was not working for him:  http://157.245.39.153/spotlight/spotlight-kenya?t=kenya_poverty_and_vulnerability&i=spotlight_on_kenya_2017.kenya_hdi&y=2014 

Choose year drop down not working
![Image from iOS (1)](https://user-images.githubusercontent.com/36768381/78769112-c9698080-7984-11ea-9d8d-04993d59f5d2.jpg)

**Comment by wakibi** [comment]
Same experience for me.

- The map seems to have a higher value for the z-index and hence the drop-downs just above it (the three as per screenshot shared by Josh) will always go behind the map div. 

- The drop-downs are not working i.e the selected values are not triggered. I thought javascript was disabled on my device, but it's the same on Safari, Chrome and Firefox. I double checked and Javascript was enabled on my device. I am sending a screen-recording on the Slack channel

**Comment by edwinmp** [comment]
@k8hughes @wakibi if you've found issues that have nothing to do with the mobile nav, please create new issues for them... as for the issues you've mentioned, there's already one for them #145

**Comment by edwinmp** [comment]
This is the mobile nav 
![image](https://user-images.githubusercontent.com/5672438/78770840-d9d72680-7997-11ea-8c08-f1ef933db7c3.png)

**Comment by k8hughes** [comment]
Ah ok - sorry Edwin, I have just check further on the last post I wrote and I think that is because of the data available as it is inthe same on desktop.

I'll close this issue now
