### ISSUE TITLE
Shared links not highlighting the map

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#139]
Map doesn’t initialise with highlighted location when browsing via a shared link with GET data such as: http://157.245.39.153/spotlight/spotlight-kenya?t=kenya_poverty_and_vulnerability&i=spotlight_on_kenya_2017.kenya_poverty_headcount&y=2016&lc=KE.d18944&ln=kirinyaga

**Comment by edwinmp** [comment]
Duplicate of #129
