### ISSUE TITLE
Compare page bugs

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#140]
Page should load with something pre selected so the graph is visable.

"Compare this location to others " button doesn’t pass current location to compare page

Compare page doesn’t update URL with selected locations to allow sharing/deep linking

Removing locations on Compare page doesn’t update graph

**Comment by edwinmp** [comment]
@davidebukali this is probably linked to what you're currently working on, that's issue #117 ... perhaps you could split them all into separate issues and close the duplicates.

**Comment by davidebukali** [comment]
> Page should load with something pre selected so the graph is visable.
> 
> "Compare this location to others " button doesn’t pass current location to compare page
> 
> Compare page doesn’t update URL with selected locations to allow sharing/deep linking
> 
> Removing locations on Compare page doesn’t update graph

@edwinmp the first 3 issues are duplicates of #117;

Created #182 for `Removing locations on Compare page doesn’t update graph` which is the only unique issue here.
