### ISSUE TITLE
Data & Sources links are broken (missing http://)

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#141]
Locations in and Data & Sources appear to be empty for all locations in Kenya

**Comment by k8hughes** [comment]
@edwinmp is this another of those issues that related to you running it from your local machine yesterday?

**Comment by edwinmp** [comment]
@k8hughes this appears functional ... only problem is that the links are broken, so I'm going to update the title to focus on that.

**Comment by edwinmp** [comment]
This is a server config issue... an update to the proper root url should fix it.
