### ISSUE TITLE
Key facts section  bug

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#143]
In Key facts for Yumbe, currency reverts to USD in Poverty, Population, Education when UGX selected in Overview

**Comment by k8hughes** [comment]
@wakibi this could be to do with the data available, can you check?

**Comment by edwinmp** [comment]
@k8hughes isn't this a duplicate of the issue u logged today?

**Comment by k8hughes** [comment]
Ah yes, I hadn't relaised that when I was moving Russells issues over from the doc.
