### ISSUE TITLE
Data bug for Butebo on compare

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#147]
No graph data for Butebo even though selected in Compare:

**Comment by k8hughes** [comment]
![Screenshot 2020-04-02 at 17 30 24](https://user-images.githubusercontent.com/36768381/78274162-af085080-7507-11ea-8513-35b9ffb72650.png)

**Comment by k8hughes** [comment]
@wakibi can you check if this is a simple `no data` issue?  If that is the case then it changes the solution...

**Comment by edwinmp** [comment]
There's no data for Butebo, and a few others ... closing this in favour of issue #118
