### ISSUE TITLE
Navigating around the spotlights

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#151]
Currently getting between the two pages of the spotlight isn't clear enough.  
Comparision page could be missed and once you get there, there is no way to go back to the spotlight.

Details of the conversation with Ben are in this isssue:  https://github.com/devinit/DIwebsite-redesign/issues/688

**Comment by edwinmp** [comment]
@benjamincoleman will the secondary menu for the spotlight pages be the same as it's been with the other pages?
![image](https://user-images.githubusercontent.com/5672438/78528878-1c0e3580-77e9-11ea-8d42-c65e38b14b9e.png)

**Comment by benjamincoleman** [comment]
@edwinmp I'll get a design for this to you :)

**Comment by BenDarby** [comment]
@benjamincoleman I've added the secondary navigation module we use across the site into the hero section for the spotlight templates so it doesn't interfere with the content below. I pushed this to the `pattern_library` branch and it can be viewed here http://development-initiatives.surge.sh/page-templates/22-spotlight

**Comment by benjamincoleman** [comment]
@edwinmp we've update the desgin to have a submenu in the header for you: http://development-initiatives.surge.sh/page-templates/22-spotlight
