### ISSUE TITLE
Initial view of the location comparison

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#152]
when you land on the page there is nothing initially until you select things, as a user I need to see something on the page that indicates what the page is for and makes it clearer to me what actions to take.

https://github.com/devinit/DIwebsite-redesign/issues/689

**Comment by k8hughes** [comment]
This issue actually linkes to https://github.com/devinit/DIwebsite-redesign/issues/693 as well, because if the page pre loaded with three locations as suggested in the dropbox video that wuld solve the problem with an empty page at initial load.

**Comment by edwinmp** [comment]
Closing in favour of issue #117
