### ISSUE TITLE
Clicking on map to select a location should update the page content

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#158]
When you click on a location on the map it should become the selected location. 

For example in the Spotlight on Kenya is the user clicked on Nairobi on the map this would then update: 

1. Location selection menu to show Nairobi as the selected location
2. The map would zoom in on Nairobi and show its constituent parts
3. Key facts would show content for Nairobi
4. Charts would show data for Nairobi

**Comment by k8hughes** [comment]
This is looking good.
