### ISSUE TITLE
Revenue chart should show current year

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#159]
<img width="429" alt="Screenshot 2020-04-03 at 12 29 18" src="https://user-images.githubusercontent.com/64877/78356081-d2360d00-75a6-11ea-8d89-8c807b5fd7e7.png">

We should see the column for 2006 highlighted on the chart below to indicate the period we are looking at.

**Comment by k8hughes** [comment]
So are we saying this chart should have the line to show the change over time as well as a bar for the distinct date?

**Comment by benjamincoleman** [comment]
> So are we saying this chart should have the line to show the change over time as well as a bar for the distinct date?

Yes, you currently see this if you hover over that chart: 

<img width="414" alt="Screenshot 2020-04-03 at 13 44 31" src="https://user-images.githubusercontent.com/64877/78362189-99e7fc00-75b1-11ea-9df1-5713e7733577.png">

And I described this function in the sketches: 

<img width="742" alt="Screenshot 2020-04-03 at 13 47 45" src="https://user-images.githubusercontent.com/64877/78362268-ba17bb00-75b1-11ea-80c6-392174ffbb32.png">

**Comment by k8hughes** [comment]
@edwinmp will this be hard to implement?  It would be good to do if it isn't complex...

**Comment by edwinmp** [comment]
Will be tricky for the line chart, but will figure it out. Shouldn't be a problem to set the drop-down & tree-map to the latest year.

**Comment by k8hughes** [comment]
LGTM.
