### ISSUE TITLE
Show the chart box as well as the message

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#163]
We want to keep the white box there, but have the message display within it, so the user knows the bound of the area that has no data. 

<img width="839" alt="Screenshot 2020-04-03 at 12 40 08" src="https://user-images.githubusercontent.com/64877/78356851-491fd580-75a8-11ea-922b-aa4398086802.png">

**Comment by edwinmp** [comment]
I'm not following ... the current design was based on what was [here](https://development-initiatives.surge.sh/page-templates/22a-spotlight-nodata), which has also changed since.

**Comment by benjamincoleman** [comment]
@edwinmp yes, it's not a bug, more an improvement. I've asked @BenDarby to update the design for this.

**Comment by BenDarby** [comment]
@benjamincoleman I updated the pattern library template to show this, we can wrap the alert in the spotlight_interactive div like so: 
```
<div class="spotlight__interactive">
                        <div class="alert alert--notice"><i role="presentation" aria-hidden="true" class="ico ico-warning-warning"></i>
                            <p>Unfortunately, we do not have data for this location</p>
                        </div>
                    </div>
```
http://development-initiatives.surge.sh/page-templates/22a-spotlight-nodata

**Comment by benjamincoleman** [comment]
@edwinmp @k8hughes we've updated the design for the 'no data' messaging so that it stays within the bounds of the interactive areas. 

This is linked to the slight change to the interactive container design to remove the red border and make the background white - https://github.com/devinit/data-hub-spotlights/issues/165

**Comment by k8hughes** [comment]
LGTM
