### ISSUE TITLE
Share this visualisation button should be a button, not a link

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#167]
When we have `<a href="#">` and some JavaScript is attached to interactions with that element it should be a `<button>` not a link, when there is no href value, or place for it to navigate to. 

When completed please assign back to me and put in the Backlog

**Comment by BenDarby** [comment]
@benjamincoleman updated the spotlight templates so the share visualisation buttons are now a `button`

**Comment by benjamincoleman** [comment]
@k8hughes another for you to assign a priority to

**Comment by edwinmp** [comment]
@benjamincoleman sorry, had moved this cos I'd worked on it. It's done now, but will keep open until the fix is deployed.

**Comment by edwinmp** [comment]
@benjamincoleman I've kept the `Compare this location...` button as a link though, cos it is. It was changed to a button on surge.

**Comment by edwinmp** [comment]
Ahh, it just looks like a button ... that's a bit confusing :)
