### ISSUE TITLE
Twitter and Facebook share links to open in new window

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#168]
Twitter and Facebook share links open in same window (would recommend new windows for these).

add `target=_blank` for these links.

**Comment by BenDarby** [comment]
@benjamincoleman I added `target=_blank` to these links

**Comment by benjamincoleman** [comment]
@k8hughes this issues is ready for you to give it a priority rating

**Comment by k8hughes** [comment]
@mariamiah can you look at this - I think it wil connect to what you have beening doing on sharing feature
