### ISSUE TITLE
Prefix for currency needs to change when the currency changes

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#178]
This is a regression:
http://157.245.39.153/spotlight/spotlight-kenya?t=kenya_poverty_and_vulnerability&i=spotlight_on_kenya_2017.kenya_hdi&y=2014 

When you select the currency change to KES on the drop down the numbers change under the heading: What resources are available? - but the prefix of US$ stays the same.

You can also see this on the Government finance tab for "What is the total revenue excluding grants of Kenya?"

Same on the spotlight on Uganda when changing to UGX

![Screenshot 2020-04-07 at 09 41 05](https://user-images.githubusercontent.com/36768381/78650522-ef285400-78b6-11ea-8ca8-811d7ff81eb6.png)

**Comment by edwinmp** [comment]
@k8hughes turns out this was a config issue ... updated the CMS, so it's fine now.

**Comment by k8hughes** [comment]
Wonderful
