### ISSUE TITLE
Update Data Page to showcase Spotlights

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#187]
We need to update the [data page](https://devinit.org/data/) on the website to showcase the spotlights. 

This page already exists, so we've updated the design: for this here: https://development-initiatives.surge.sh/page-templates/21-data-section

This re-uses an element from the 'Place' template - https://development-initiatives.surge.sh/page-templates/08-1a-place, which maybe has been been used for the [Uganda page](https://devinit.org/what-we-do/where-we-work/our-work-uganda/) on the site here although the image / text is the other way around to how they appear in the design. 

The model should have: 

- box title - text field
- box content - rich text
- image
- button label
- button url

**Comment by k8hughes** [comment]
http://178.128.102.213/data/?nav=header 

This is looking good.
