### ISSUE TITLE
Country Spotlights page

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#188]
We have a new template, T24 for the spotlights page. 

This was based on the IA / sketch here; 

![Spotlights-page](https://user-images.githubusercontent.com/64877/78785949-e5c6e680-799f-11ea-8d79-a36a0e8d86fb.png)

The design is here: 

https://development-initiatives.surge.sh/page-templates/24-country-spotlights

As you can see from the IA this page is a child of the [Data page](https://devinit.org/data/). 

The spotlights and location comparisons are children of this (Country Spotlights) page. 

The page model would contain: 

- hero title
- hero intro - optional
- submenu - automatically lists all children of https://devinit.org/data/
- page content - rich text
- repeatable country blocks, so you can add as many countries as you like. For each block you would have: 
    - block title
    - block content - rich text
    - up to two page blocks which link to spotlight / comparison pages each containing: 
        - block image
        - block title
        - block content - rich text
        - block link

**Comment by k8hughes** [comment]
Can we have the box,s on this page showing pictures of the maps?  Would we do that by uploading images in the CMS or would you do something programatically?

**Comment by edwinmp** [comment]
@k8hughes adding images to the hero in the CMS does that ... I've added one.

**Comment by k8hughes** [comment]
Perfect.  I think we should have images of the maps - would you like me to do this?

**Comment by edwinmp** [comment]
Sure, if comms doesn't already have something planned :)

**Comment by k8hughes** [comment]
[Spotlights landing page text.docx](https://github.com/devinit/data-hub-spotlights/files/4516832/Spotlights.landing.page.text.docx)

Attached is the copy for this page.  Note the change to the page title for SEO purposes.

**Comment by k8hughes** [comment]
![Uganda spotlight](https://user-images.githubusercontent.com/36768381/80184868-49d5e580-8603-11ea-8b71-ca831017c3be.PNG)
![Kenya spotlight 2](https://user-images.githubusercontent.com/36768381/80184872-4c383f80-8603-11ea-8f7d-ed5e4cdb69ef.PNG)

Please can we add these images to the page?

**Comment by edwinmp** [comment]
@k8hughes these will be added to the hero of the Country Spotlights page, so it's not a code change - shouldn't hold up the issue.

**Comment by edwinmp** [comment]
@k8hughes these will need to be proper hero images, otherwise they'll turn out strange ... uploaded them.
