### ISSUE TITLE
Remove chart button for location comparison

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#197]
We need to give the user the ability to remove a chart from the location comparison template. 

Live version here: http://157.245.39.153/spotlight/spotlight-kenya/compare

Template is here: http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

Sketch for this with the new button feature is here: https://marvelapp.com/d36178e/screen/67899660

Whilst we're looking at this, I think it would be good to tie the controls to the box a bit more - so I've included a background to the top, which should join to the chart container. You can see this in the [sketch](https://marvelapp.com/d36178e/screen/67899660).

Also, a couple of CSS things to tweak: 

Odd left padding on form controls in header of each chart: 

<img width="414" alt="Screenshot 2020-04-10 at 11 43 10" src="https://user-images.githubusercontent.com/64877/78985457-c4d9cf00-7b20-11ea-8a76-580425d96a99.png">

Odd left padding on the visualisation divs: 

<img width="741" alt="Screenshot 2020-04-10 at 11 43 33" src="https://user-images.githubusercontent.com/64877/78985480-d3c08180-7b20-11ea-909d-66005b65bc62.png">

**Comment by BenDarby** [comment]
@benjamincoleman I added the remove chart button as per sketch and fixed those minor spacing issues with CSS as requested :) 
http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

**Comment by BenDarby** [comment]
@benjamincoleman We already have a class in place for giving the header section of a chart a background colour that joins it to the charts. It requires a slight markup change but it's just changing the name of the class, we change `space-section-bottom--small` to `spotlight-banner` within the `spotlight div` and that will apply the desired style. 
You can see it here for reference: http://development-initiatives.surge.sh/page-templates/23-spotlight-location-comparison

**Comment by benjamincoleman** [comment]
@k8hughes @edwinmp we've added a "remove" button for this issue, and slightly updated the style swapping out a class as @BenDarby described above. This keeps the controls and the charts a little more unified.

**Comment by k8hughes** [comment]
This is looking nice and working as intended.
