### ISSUE TITLE
Spotlights template

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#204]
I've set up a new template using existing modules for the new Spotlights page in the DI site. This links to the two spotlight apps. I have a problem with the 2-col cards though, where if there is no excerpt, they lose their width: 

<img width="1263" alt="Screenshot 2020-04-17 at 11 40 21" src="https://user-images.githubusercontent.com/64877/79561063-94ee7680-80a0-11ea-98b8-44d8ada3d1a3.png">

<img width="1375" alt="Screenshot 2020-04-17 at 11 40 30" src="https://user-images.githubusercontent.com/64877/79561073-9a4bc100-80a0-11ea-99aa-3ed98c151590.png">

**Comment by BenDarby** [comment]
@benjamincoleman pushed a fix by changing the width to 100% when using grid
