### ISSUE TITLE
Methodology page

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#208]
This is just a general page.  There is one methodology page for both spotlights, linked to from the `Data and sources` section at the bottom of the page.

Here is the content.
[Spotlights Methodology page _edits accepted.docx](https://github.com/devinit/data-hub-spotlights/files/4514741/Spotlights.Methodology.page._edits.accepted.docx)

**Comment by edwinmp** [comment]
Added these ...

**Comment by k8hughes** [comment]
http://178.128.102.213/data/methodology/ 

This LGTM.
