### ISSUE TITLE
Making the API HTTPS

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#216]
Need to get a subdomain pointing to those IPs, @akmiller01  might be able to help @wakibi get access to the Linode account

**Comment by akmiller01** [comment]
Done: https://api.devinit.org/

Just waiting on a push to the Spotlight code to switch from the API IP to the domain name.

**Comment by akmiller01** [comment]
And doubly done. Cheers @edwinmp

**Comment by wakibi** [comment]
Working as expected. Closing this issue
