### ISSUE TITLE
Update Uganda Key Facts sections with new data

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#252]
Below are the key facts sections (for country & individual locations). The text in italics is the table name for each key fact's data table

@wakibi feel free to remove those that Moses doesn't have updated data for.

### **Country Key Facts**

**Government Finance**

- [ ] What is the total revenue excluding grants of Uganda? - _domestic_

- [ ] How much government revenue comes from external grants (AID)? - _domestic_

**Poverty**

- [ ] Is Poverty reducing over time? - _depth_of_extreme_poverty_190_

- [ ] How Deep is Poverty? - _depth_of_extreme_poverty_190_

**Population**

- [ ] What is the population? - _population_total_

- [ ] What is the urban vs rural split? - _population_rural_urban_

- [ ] What is the age profile? - _population_by_age_

**Overview**

- [ ] How many of the poorest people globally live in Uganda? - _poorest_20_percent_

- [ ] How much does the government spend per person per annum? - _govt_spend_pc_

- [ ] What resources are available? - _domestic_

### **Location Key Facts**

**Health**

- [ ] How much local government healthcare funding is there per person? - _uganda_health_funding_

- [ ] What percentage of tuberculosis cases have been successfully treated? - _uganda_tb_success_

- [ ] What is the district league health performance score? - _uganda_overall_health_

**Education**

- [ ] What is the pupil-teacher ratio in primary education? - _uganda_primary_stu_teach_ratio_gov_

- [ ] How much primary education funding is there per pupil? - _uganda_primary_educ_funding_

- [ ] What percentage of students pass the primary leaving exam? - _uganda_leaving_exam_perf_rate_

- [ ] What percentage of students pass the primary leaving exam? - _uganda_leaving_exam_perf_rate_

**Poverty**

- [ ] What is the standard of living score? - _uganda_deprivation_living_

- [ ] What is the average life expectancy? - _uganda_life_expectancy_

- [ ] What percentage of people in {LOCATION} live below the national poverty line? - _uganda_poverty_headcount_

**Overview**

- [ ] How much does the government spend per person? - _uganda_gov_spend_pp_

- [ ] What resource are available to local governments in {LOCATION}? - _uganda_igf_resources_

- [ ] What percentage of people in {LOCATION} live below the national poverty line? - _uganda_poverty_headcount_

**Comment by k8hughes** [comment]
@wakibi please can you update this issue to say what data you have recieved and if it is in process?

**Comment by wakibi** [comment]
> Below are the key facts sections (for country & individual locations). The text in italics is the table name for each key fact's data table
> 
> @wakibi feel free to remove those that Moses doesn't have updated data for.
> 
> ### **Country Key Facts**
> **Government Finance**
> 
> * [*]  What is the total revenue excluding grants of Uganda? - _domestic_  **2019**
> * [*]  How much government revenue comes from external grants (AID)? - _domestic_  **2019**
> 
> **Poverty**
> 
> * [ ]  Is Poverty reducing over time? - _depth_of_extreme_poverty_190_
> * [ ]  How Deep is Poverty? - _depth_of_extreme_poverty_190_
> 
> **Population**
> 
> * [*]  What is the population? - _population_total_ **2021**
> * [ ]  What is the urban vs rural split? - _population_rural_urban_
> * [ ]  What is the age profile? - _population_by_age_
> 
> **Overview**
> 
> * [ ]  How many of the poorest people globally live in Uganda? - _poorest_20_percent_
> * [*]  How much does the government spend per person per annum? - _govt_spend_pc_ - **2020**
> * [ ]  What resources are available? - _domestic_
> 
> ### **Location Key Facts**
> **Health**
> 
> * [ ]  How much local government healthcare funding is there per person? - _uganda_health_funding_
> * [ ]  What percentage of tuberculosis cases have been successfully treated? - _uganda_tb_success_
> * [ ]  What is the district league health performance score? - _uganda_overall_health_
> 
> **Education**
> 
> * [ ]  What is the pupil-teacher ratio in primary education? - _uganda_primary_stu_teach_ratio_gov_
> * [ ]  How much primary education funding is there per pupil? - _uganda_primary_educ_funding_
> * [ ]  What percentage of students pass the primary leaving exam? - _uganda_leaving_exam_perf_rate_
> * [ ]  What percentage of students pass the primary leaving exam? - _uganda_leaving_exam_perf_rate_
> 
> **Poverty**
> 
> * [ ]  What is the standard of living score? - _uganda_deprivation_living_
> * [ ]  What is the average life expectancy? - _uganda_life_expectancy_
> * [ ]  What percentage of people in {LOCATION} live below the national poverty line? - _uganda_poverty_headcount_
> 
> **Overview**
> 
> * [ ]  How much does the government spend per person? - _uganda_gov_spend_pp_
> * [ ]  What resource are available to local governments in {LOCATION}? - _uganda_igf_resources_
> * [ ]  What percentage of people in {LOCATION} live below the national poverty line? - _uganda_poverty_headcount_

See responses above (with new end years). Please note that some of them look "illogical" and it's part of the reason I delayed to update this issue. Moses says previously we were using World Bank data, but are now using mainly UBOS data hence the discrepancy. A good example is gov_spend_pc has 220 for 2020, yet 2018 had 431

**Comment by Mozmitch** [comment]
@Chris, about the discrepancy in the data (WB Vs. UBOS) I suggest we change all historical data from WB to UBOS. This is already provided in the Key facts excel file I shared. Look that the 'data' sheet row 57

**Comment by Mozmitch** [comment]
@wakibi also change the year from 2019 to 2020 as we are updating date from 2017 thru 2020. If possible we shall neet a tool tip to explain that the data from 2019-2020 are projections

**Government Finance**

 What is the total revenue excluding grants of Uganda? - **domestic 2020**
 How much government revenue comes from external grants (AID)? - **domestic 2020**

**Comment by wakibi** [comment]
Hi @Mozmitch, those changes you asked for are done via the CMS. Log in and modify them as per your expectations. Cheers

**Comment by wakibi** [comment]
Closing this as @Mozmitch is happy now.
