### ISSUE TITLE
Data inconsistencies for Financing in Uganda

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#254]
1. 2006 data is negative (NB: it was this way even on the old data hub)

2. Sharp decline from 2015 - 2018 (this is because of disparities between budget type data)

3. Using projected data for 2018 despite having approved data

Perhaps we should get rid of this whole `project, actual, proposed` data thing. At the very least, we should provide ONLY one for each year i.e if we have projected and get approved data, we replace the projected with the approved. I remember Moses mentioning something along these lines the last time we discussed this @wakibi 

NB: Moses implied that there is 2019 data, but it's not in the DB

**Comment by k8hughes** [comment]
@wakibi please can you update this issue to say what data you have recieved and if it is in process?

**Comment by edwinmp** [comment]
Fix the frontend side of this. The line chart is now stable, with only the value of a specific year changing when the budget type is updated.
http://161.35.43.45/spotlight/spotlight-uganda

**Comment by k8hughes** [comment]
@edwinmp what do we need to do next for this issue?

**Comment by edwinmp** [comment]
Moses pointed out three issues below ... at the very least, if the data is not accurate, we'll need the accurate data. We'd also decided to only have one budget type per year i.e if we have actual data, we get rid of the projected.

> * 2006 data is negative (NB: it was this way even on the old data hub)
> * Sharp decline from 2015 - 2018 (this is because of disparities between budget type data)
> * Using projected data for 2018 despite having approved data

**Comment by k8hughes** [comment]
Ok so I think this is the part where we need @wakibi to let us know if he got the data from Moses or not.

**Comment by wakibi** [comment]
Hi @k8hughes , for the budgets I haven't got new data, but also this is part of what Moses will be verifying so we can remove the obsolete data and remain with only one budget type as @edwinmp noted above. I am already working on a script to remove the obsolete data and will run it once Moses confirms what needs to be removed.

**Comment by wakibi** [comment]
Everything here has been addressed. Moses is happy. Closing issue.
