### ISSUE TITLE
Design database schema and relationships

### ISSUE THREAD

**Issue by davidebukali** [devinit/data-hub-spotlights#3]

**Comment by Napho** [comment]
Spotlight already has pre-existing data working powering the datahub, this issue will involve making adjustments where necessary to fit the purpose of geo queries as desired by the website. Very much database normalisation as opposed to a complete redesign

**Comment by k8hughes** [comment]
@wakibi  I think you are working on this already,do we need this issue or do you already have another issue where you are managing this work?

**Comment by k8hughes** [comment]
This has been done.
