### ISSUE TITLE
Add share button & related functionality to map section

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#48]
- [x] Add button

- [x] Record selected topic, indicator and year in URL

- [x] On page refresh, retain selection

- [x] Generate share link

- [x] Share on facebook, twitter, email

On step 2, use Next.JS shallow routing https://nextjs.org/docs/routing/shallow-routing. For step 3, retrieve query parameters via the `query` property of the NextJS `router` prop.

**Comment by k8hughes** [comment]
This is from Russells testing - not sure if it should go here or on a separate issue: 


 Share this visualisation bit.ly link doesn’t convey selected location (Mpigi selected in this instance): https://bit.ly/2Juegyl

**Comment by k8hughes** [comment]
Twitter and Facebook share links open in same window (would recommend new windows for these)

**Comment by k8hughes** [comment]
When I click share to facebook, it does open in a new window, but the auto generated text has weird things in like "no data" .  See screen shot below
![Screenshot 2020-04-08 at 10 48 09](https://user-images.githubusercontent.com/36768381/78770487-89a39880-7986-11ea-91ad-951a7ed574e1.png)

**Comment by edwinmp** [comment]
That looks like a snapshot of the page content, what you get when you paste links in places ... can't do anything about that. Actually surprised it's showing anything at all... then again, it's facebook ... must have special ways of crawling web apps as well.
