### ISSUE TITLE
Add functional menu widget to Map Section

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#54]
Dependent on issue #51

**Comment by k8hughes** [comment]
I'm not sure what I should be testing here, can you give me an idea of what I should see as a user then I can check it.

**Comment by edwinmp** [comment]
I think you only need to test behaviour & appearance of the menu ... if there's anything you find lacking, please log a comment.
Behaviour includes:
- Move through every level of the menu
- Allow to view valid locations. Menu items that don't affect the map should not have the view button
- Can reset the map by clicking view on the main menu item i.e Uganda, Kenya
- When view is clicked, the menu is closed and the map is updated to the specific location, which is displayed on the menu

![image](https://user-images.githubusercontent.com/5672438/76001516-42089780-5f16-11ea-9646-30d56e3cc225.png)

**Comment by k8hughes** [comment]
There is one weird bug with this, let me try to write out the steps to reproduce it:
1. select south buganda
2.select Masaka
3. Map zooms to show Masaka
4. select Elgon
5. select kween
6. Map doesn't zoom if the second area selected is on longer on screen after the first zoom, you have to zoom the map out to see your select area and manually zoom in

**Comment by edwinmp** [comment]
Nice catch ... I'd seen it before, but hadn't figured out how to replicate it. I don't think this is menu issue ... it's tied to issue #74

**Comment by edwinmp** [comment]
> There is one weird bug with this, let me try to write out the steps to reproduce it:
> 
> 1. select south buganda
>    2.select Masaka
> 2. Map zooms to show Masaka
> 3. select Elgon
> 4. select kween
> 5. Map doesn't zoom if the second area selected is on longer on screen after the first zoom, you have to zoom the map out to see your select area and manually zoom in

@k8hughes this should be fixed now.

**Comment by k8hughes** [comment]
Excellent - nice work, this is now working as intended.
