### ISSUE TITLE
Allow uneven configuration of indicator years

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#63]
Some indicators do not have data for certain years, so it'd be best to exclude them.
Add field on the Wagtail CMS for managing this ... Since we already have a `start_year` and `end_year` field, an `exclude_years` field seems ideal.

**Comment by edwinmp** [comment]
### On CMS
CMS repo https://github.com/devinit/DIwebsite-redesign

- In the [`SpotlightIndicator`](https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/spotlight/models.py#L63) model, add a new field `excluded_years`, right under [`end_year`](https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/spotlight/models.py#L86) ... it should be a TextField, null & blank with a help_text="Comma separated values e.g. 2002,2004,2017".
- To ensure that this field is returned via the API, add it [here](https://github.com/devinit/DIwebsite-redesign/blob/develop/di_website/api/utils.py#L98) after `end_year`.

**NB:** Add migrations to their own commit

## On Spotlights
- Update [`SpotlightIndicator`](https://github.com/devinit/data-hub-spotlights/blob/develop/utils/data.ts#L34) typing to include `excluded_years`
- Update map section and location comparison year drop downs to exclude the years specified in this field.

**Comment by k8hughes** [comment]
This seems to be working.  I tried many configuarations and no longer had the ability to select years with no data.
