### ISSUE TITLE
What colour should be on the map legend for "no data"?

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#69]
Currently the legend says that white is the colour for "no data" but on the maps the distrcits with no data are coming up as grey.

Either we need to add grey to the map legend or we need to change the colour on the map for "no data" to be white.

**Comment by edwinmp** [comment]
@mariamiah please look at this one as well.

**Comment by edwinmp** [comment]
@k8hughes this should be fixed

**Comment by k8hughes** [comment]
Yup, LGTM :)
