### ISSUE TITLE
No way to deselect a district

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#70]
If I use the district drop down in the header - how do I clear this so I can see everything on the map again?  

Currently once I select a district I can't work out how to go back to seeing everything on the map.

**Comment by benjamincoleman** [comment]
@k8hughes this seems to deviate from the designs, am I to assume you can use the dropdown to navigate to a level, at which point said dropdown content is replaced with the constituent parts of the selected level? If so I can see the dilemma as you can only 'zoom in' and not 'zoom out'. A button to send you "up a level" would be needed, or an title / link to the selected area would allow you to move up. Or a breadcrumb would give you the ability to move up more than one level.

**Comment by k8hughes** [comment]
@edwinmp @davidebukali 
I see what Ben means - we havent done the seletion menu in the same way as the pattern library design.  Do you know why this change was made?  I've screen shot the pattern library design - it always keeps Uganda at the top so it is easy to go back to the full map.

Given time pressures I doubt we have time to redo the menu the correct way right now but we should maybe revisit this after open data day.  What do you think?

![Screenshot 2020-02-26 at 10 09 28](https://user-images.githubusercontent.com/36768381/75334637-1d5e5100-5880-11ea-93bb-12a2ea17947b.png)

**Comment by edwinmp** [comment]
The issue for this is still in progress #20

**Comment by edwinmp** [comment]
@k8hughes  This should be fixed.

**Comment by k8hughes** [comment]
Yes, I check it on it works
