### ISSUE TITLE
Location name in key facts section should not be in caps

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#73]
![Screenshot 2020-02-26 at 16 21 51](https://user-images.githubusercontent.com/36768381/75365027-8364cb80-58b4-11ea-86b7-66902df7af78.png)
In the pattern library it is meant to be Sentance case not caps.  Screen shot of pattern library and staging side by side for context.

**Comment by edwinmp** [comment]
@mariamiah could you please have a look at this ...  it shouldn't be in caps in the menu as well. This should upgrade your troubleshooting skills :)
