### ISSUE TITLE
Click and zoom on the map

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#74]
As a user I want to be able to click on an area on the map and it zoom in.

I think we had this functionality on an earlier protype video

**Comment by edwinmp** [comment]
@k8hughes at the moment, we're not showing the sub-counties on zoom since we don't yet have the data. I would really love some honest feedback on this one ... for example:
- is the default zoom level enough?
- Would you want the user to be able to zoom out even further?
- Should we only show the highlight location, or keep it as is (focused on highlighted, with the rest of the map disabled)

**Comment by edwinmp** [comment]
Oh, I found a way of doing this without requiring any potentially billable services, so we're safe there :)

**Comment by k8hughes** [comment]
Nice work.  I think the deafult is the right level.  No need to zoom out further.

```Should we only show the highlight location, or keep it as is (focused on highlighted, with the rest of the map disabled)``` I think leep it as it is.

**Comment by k8hughes** [comment]
I don't think this has been deployed.  I just went to test the click and zoom but it didn't seem to be working.

**Comment by edwinmp** [comment]
At all? Deployed that yesterday ... try clearing your cache.

**Comment by k8hughes** [comment]
I've clear my cache and tried this on both chrome and firefox, these are my steps:
1. Load spotlight page
2. Click the province location that I want to select / zoom in on
expectation - it should select this area, but currently nothing happens.  Does it work for you?

**Comment by edwinmp** [comment]
It works for me ... I think it may be a location specific issue. I configured spotlight on Uganda to base off 2016 district names, so some of the new ones may not show anything.
Could u test with the Spotlight on Kenya and see if u can replicate it there.

**Comment by edwinmp** [comment]
@k8hughes apologies for the confusion. Just deployed the feature.

**Comment by k8hughes** [comment]
This looks good to me :)
