### ISSUE TITLE
Decimal places in the key facts area

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#77]
![Screenshot 2020-02-27 at 09 40 44](https://user-images.githubusercontent.com/36768381/75432097-cae76800-5945-11ea-8bd2-fc4d6624b466.png)

We need to review the use of decimal places for the key facts, eg as you can see in this screen shot of the pattern library and the staging site side by side "place overal" is a ranking so should not have a decimal place.  Other stats have one decimal place.

**Comment by edwinmp** [comment]
I'll add a configuration for this, cos some data may benefit from having more or less decimal places.

**Comment by k8hughes** [comment]
Excellent thanks Edwin, that sounds like the best approach.

**Comment by k8hughes** [comment]
LGTM
