### ISSUE TITLE
Menu implementation error - we have done "select" instead of "search"

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#89]
![Screenshot 2020-03-03 at 09 54 51](https://user-images.githubusercontent.com/36768381/75764146-57729b80-5d35-11ea-8888-ea77a88bab17.png)

I've added a screen shot of the pattern library next to staging.  As you can see from the pattern library the second menu in that top section should be for search not to select.  As a user it is very confusing to have two selects next to each other when you can only select one thing at a time.  If we don't have tie to implement search yet we should remove this second menu selector until it can be search as intended.

**Comment by edwinmp** [comment]
@k8hughes that is the search widget ... it's the text that's misleading ... I'll change it to `Search for a location` ... will make it asynchronous as well so that the dropdown doesn't show up on initial click.

**Comment by edwinmp** [comment]
@k8hughes this should be fixed now.

**Comment by k8hughes** [comment]
Yep, this LGTM.
