### ISSUE TITLE
Different cases used between Kenya and Uganda menus

### ISSUE THREAD

**Issue by k8hughes** [devinit/data-hub-spotlights#93]
For the Uganda menu it is all in capitals and then on the kenya menu we use Sentance case. 
In the Kenya menu, after a selection is made it then reverts to caps.

**Comment by k8hughes** [comment]
![Screenshot 2020-03-05 at 16 45 52](https://user-images.githubusercontent.com/36768381/76004722-dfa59c00-5f01-11ea-9813-aa361c18ac71.png)
![Screenshot 2020-03-05 at 16 46 03](https://user-images.githubusercontent.com/36768381/76004729-e207f600-5f01-11ea-8a10-4df5a9e0f872.png)

**Comment by edwinmp** [comment]
@mariamiah is already working on this through issue #73 , but it's better to have an issue of its own.

**Comment by k8hughes** [comment]
There are still some inconsistencies.  In the main menu, the top level ie country name is in capitals, then the next level down is in sentance case, then when you select it turns into capitals.
Can we keep consistency?

**Comment by benjamincoleman** [comment]
@k8hughes it should be Sentence Case, sorry for the confusion

**Comment by k8hughes** [comment]
@mariamiah can you have another look at this one please? Thanks :)

**Comment by mariamiah** [comment]
Alright, I am going to look at it

**Comment by k8hughes** [comment]
Brilliant this looks good now :)
